config/routes.rb
Rails.application.routes.draw do
  get 'oauths/oauth'
  get 'oauths/callback'
  get 'admin_panel/index'
  root 'courses#index'

  resources :courses
  resources :users
  resources :sessions
  resources :admin_panel

  get "logout" => "sessions#destroy", :as => "logout"
  get "login" => "sessions#new", :as => "login"
  get "signup" => "users#new", :as => "signup"

  post "oauth/callback" => "oauths#callback"
  get "oauth/callback" => "oauths#callback"
  get "oauth/:provider" => "oauths#oauth", :as => :auth_at_provider

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/authentication.rb
class Authentication < ApplicationRecord
  belongs_to :user
end

app/models/check_in.rb
# == Schema Information
#
# Table name: check_ins
#
#  id         :bigint           not null, primary key
#  lesson_id  :bigint           not null
#  user_id    :bigint           not null
#  present    :boolean          default(FALSE)
#  note       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class CheckIn < ApplicationRecord
  belongs_to :lesson
  belongs_to :user
end

app/models/course.rb
# == Schema Information
#
# Table name: courses
#
#  id          :bigint           not null, primary key
#  name        :string
#  description :text
#  status      :string
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Course < ApplicationRecord
  has_many :course_users
  has_many :users, through: :course_users
  has_many :lessons
end

app/models/course_user.rb
# == Schema Information
#
# Table name: course_users
#
#  id         :bigint           not null, primary key
#  course_id  :bigint
#  user_id    :bigint
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class CourseUser < ApplicationRecord
  belongs_to :course
  belongs_to :user
end

app/models/lesson.rb
# == Schema Information
#
# Table name: lessons
#
#  id          :bigint           not null, primary key
#  theme       :string
#  description :text
#  time        :datetime
#  course_id   :bigint
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Lesson < ApplicationRecord
  belongs_to :course
  has_many :check_ins
  has_many :users, through: :check_ins
end

app/models/user.rb
class User < ApplicationRecord
  #attr_accessible :email, :password, :password_confirmation, :crypted_password, :authentications_attributes
  authenticates_with_sorcery! do |config|
    config.authentications_class = Authentication
  end

  has_many :authentications, :dependent => :destroy
  accepts_nested_attributes_for :authentications

  has_many :course_users
  has_many :courses, through: :course_users
  has_many :check_ins
  has_many :lessons, through: :check_ins

  validates :password, length: { minimum: 3 }, if: -> { new_record? || changes[:crypted_password] }
  validates :password, confirmation: true, if: -> { new_record? || changes[:crypted_password] }
  validates :password_confirmation, presence: true, if: -> { new_record? || changes[:crypted_password] }
  validates :email, presence: true, uniqueness: true, format: { with: URI::MailTo::EMAIL_REGEXP }

end

app/controllers/admin_panel_controller.rb
class AdminPanelController < ApplicationController
  before_action :admin_verify

  def index
    @users = User.all
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  private
  def admin_verify
    redirect_to root_path unless current_user&.admin?
  end
  def not_authenticated
    redirect_to login_path, alert: "Please login first"
  end
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :set_course, only: %i[show]

  def index
    @courses = Course.all
  end

  def show; end

  private

  def set_course
    @courses = Course.find(params[:id])
  end
end

app/controllers/oauths_controller.rb
class OauthsController < ApplicationController

  # sends the user on a trip to the provider,
  # and after authorizing there back to the callback url.
  def oauth
    login_at(auth_params[:provider])
  end

  def callback
    provider = auth_params[:provider]
    if @user = login_from(provider)
      redirect_to root_path, :notice => "Logged in from #{provider.titleize}!"
    else
      begin
        @user = create_from(provider)
        # NOTE: this is the place to add '@user.activate!' if you are using user_activation submodule

        reset_session # protect from session fixation attack
        auto_login(@user)
        redirect_to root_path, :notice => "Logged in from #{provider.titleize}!"
      rescue
        redirect_to root_path, :alert => "Failed to login from #{provider.titleize}!"
      end
    end
  end

  private
    def auth_params
    params.permit(:code, :provider)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  def create
    @user = login(params[:email], params[:password], params[:remember_me])
    if @user
      redirect_to root_path, notice: "Logged in!"
    else
      redirect_to new_session_path, notice: "Email or password was invalid"
    end
  end

  def destroy
    logout
    redirect_to root_url, :notice => "Logged out!"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[show edit update destroy]
  before_action :admin_verify, only: [:edit, :update, :destroy]
  def show; end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to login_path, notice: 'User was successfully created.'
    else
      render :new
    end
  end

  def edit; end

  def update
    if @user.update(user_params)
      redirect_to admin_panel_index_path, notice: 'User was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @user.destroy
    redirect_to admin_panel_index_path, notice: 'User was successfully destroy.'
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation, :crypted_password, :salt,
                                 :first_name, :last_name, :admin)
  end
end

app/helpers/admin_panel_helper.rb
module AdminPanelHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/oauths_helper.rb
module OauthsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin_panel/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>
<table>
  <thead>
  <tr>
    <th>Email</th>
    <th>Name</th>
    <th>Admin?</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <% @users.each do |user| %>
    <tr>
      <td><%= user.email %></td>
      <td><%= user.first_name %> <%= user.last_name %></td>
      <td><%= user.admin %></td>
      <td><%= link_to 'Show', user %></td>
      <td><%= link_to 'Edit', edit_user_path(user) %></td>
      <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/courses/index.html.erb
<h1>index</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Thinkiny</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <%= render 'shared/navbar' %>
  <%= render 'shared/message' %>
    <%= yield %>
  </body>
</html>

app/views/oauths/callback.html.erb
<h1>Oauths#callback</h1>
<p>Find me in app/views/oauths/callback.html.erb</p>

app/views/oauths/oauth.html.erb
<h1>Oauths#oauth</h1>
<p>Find me in app/views/oauths/oauth.html.erb</p>

app/views/shared/_message.html.erb
<% if notice != nil  %>
  <p class="alert alert-secondary text-sm-center" role="alert"><%= notice %></p>
<% elsif alert != nil %>
  <p class="alert alert-secondary text-sm-center" role="alert"><%= alert %></p>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <%= link_to 'Home', root_path, class: 'navbar-brand' %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav ml-auto">
      <% if current_user %>
        <% if current_user&.admin? %>
          <li class="nav-item active">
            <%= link_to 'AdminPanel', root_path, class: 'nav-link' %>
          </li>
        <% else %>
          <li class="nav-item active">
            <span class="nav-link"><%= current_user.email %></span>
          </li>
        <% end %>
        <li class="nav-item">
          <%= link_to "Log out", logout_path, class:'nav-link' %>
        </li>
      <% else %>
        <li class="nav-item active">
          <%= link_to "Log in", login_path , class:'nav-link'%>
        </li>
        <li class="nav-item">
          <%= link_to "Sign up", signup_path, class:'nav-link' %>
        </li>
      <% end %>
    </ul>
  </div>
</nav>

app/views/users/_admin_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <ul>
        <% user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="row" style="margin-top: 20px">
    <div class="col-sm-5 offset-sm-1">
      <div class="form-group row"  >
        <%= form.label :first_name, class:"col-sm-3 col-form-label" %>
        <div class="col-sm-6">
          <%= form.text_field :first_name, class:"form-control" %>
        </div>
      </div>
      <div class="form-group row"  >
        <%= form.label :last_name, class:"col-sm-3 col-form-label" %>
        <div class="col-sm-6">
          <%= form.text_field :last_name, class:"form-control" %>
        </div>
      </div>
      <div class="form-group row"  >
        <%= form.label :email, class:"col-sm-3 col-form-label" %>
        <div class="col-sm-6">
          <%= form.email_field :email, class:"form-control" %>
        </div>
      </div>
      <!-- <div class="form-group offset-lg" >
        <%#= form.label :image, "Загрузите автарку", class:"col-form-label" %>
        <%#= form.file_field :image %>
      </div>-->
    </div>
    <div class="col-sm-5 offset-sm-1">
      <div class="form-group row"  >
        <%= form.label :admin, class:"col-sm-3 col-form-label" %>
        <div class="col-sm-1">
          <%= form.check_box :admin, class:"form-control" %>
        </div>
      </div>
      <div class="actions" style="padding-top: 15px">
        <%= form.submit class:"btn btn-outline-dark" %>
        <%= link_to 'back', _back_url , class:"btn btn-outline-dark" , style:"margin-left: 10px;"%>
      </div>
<% end %>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <div class="offset-sm-3 mt-4">
    <% if user.errors.any? %>
      <div id="error_explanation">
        <ul>
          <% user.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
  </div>
  <div class="row mt-5" >
    <div class="col-sm-5 offset-sm-1">
      <div class="form-group row"  >
        <%= form.label :first_name, class:"col-sm-3 col-form-label" %>
        <div class="col-sm-6">
          <%= form.text_field :first_name, class:"form-control" %>
        </div>
      </div>
      <div class="form-group row"  >
        <%= form.label :last_name, class:"col-sm-3 col-form-label" %>
        <div class="col-sm-6">
          <%= form.text_field :last_name, class:"form-control" %>
        </div>
      </div>
      <div class="form-group row"  >
        <%= form.label :email, class:"col-sm-3 col-form-label" %>
        <div class="col-sm-6">
          <%= form.email_field :email, class:"form-control" %>
        </div>
      </div>
    </div>
    <div class="col-sm-5 offset-sm-1">
      <div class="form-group row"  >
        <%= form.label :password, class:"col-sm-3 col-form-label" %>
        <div class="col-sm-6">
          <%= form.password_field :password, class:"form-control" %>
        </div>
      </div>
      <div class="form-group row"  >
        <%= form.label :password_confirmation, class:"col-sm-3 col-form-label" %>
        <div class="col-sm-6">
          <%= form.password_field :password_confirmation, class:"form-control" %>
        </div>
      </div>
      <div class="actions" style="padding-top: 15px">
        <%= form.submit class:"btn btn-outline-dark" %>
        <%= link_to 'back', root_path , class:"btn btn-outline-dark" , style:"margin-left: 10px;"%>
      </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>
<%= render 'admin_form', user: @user %>

app/views/users/new.html.erb
<h1>New User</h1>
<%= render 'form', user: @user %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>First name:</strong>
  <%= @user.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @user.last_name %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>